services:
  db:
    image: postgres:latest
    container_name: mathearn-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${MATH_EARN_DB_NAME}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build: ./MathEarn.API
    container_name: mathearn-backend
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db;Database=${MATH_EARN_DB_NAME};User Id=${DB_USER};Password=${DB_PASSWORD};
    depends_on:
      db:
        condition: service_healthy
  frontend:
    build: ./math-earn
    container_name: mathearn-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:5173"  # Vite default dev port
    volumes:
      - ./math-earn:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true  # Fix for hot-reloading in Docker
      - VITE_PORT=5173 
volumes:
  postgres_data: